# port_registry.py
import subprocess, json, os, time, urllib.request

PORT_RANGE = range(3000, 4000)
REGISTRY_FILE = "ports.json"
APACHE_BRANCHES_CONF = "apache/branches.conf"
GATEWAY_CONTAINER = "simmsilos-gateway"
DOCKER_NETWORK = "simmsilos-net"


def _render_apache(registry):
    blocks = []
    for branch in registry:
        blocks.append(
            f"""<Location /branch/{branch}/>
    ProxyPass        http://simmsilos-{branch}:3000/
    ProxyPassReverse http://simmsilos-{branch}:3000/
    RequestHeader set X-Branch "{branch}"
</Location>
"""
        )
    return "# generated by port_registry.py — do not edit by hand\n" + "\n".join(blocks)


def _reload_gateway():
    # graceful reload picks up the new branches.conf without dropping connections.
    # if the gateway isn't running yet (first run before `docker compose up`), this is a no-op.
    result = subprocess.run(
        ["docker", "exec", GATEWAY_CONTAINER, "httpd", "-k", "graceful"],
        capture_output=True, text=True
    )
    if result.returncode != 0 and "No such container" not in result.stderr:
        print(f"Warning: gateway reload failed: {result.stderr.strip()}")


def _sync_gateway():
    registry = load()
    os.makedirs("apache", exist_ok=True)
    with open(APACHE_BRANCHES_CONF, "w") as f:
        f.write(_render_apache(registry))
    _reload_gateway()
    print(f"Apache config updated ({len(registry)} branches)")


def load():
    if not os.path.exists(REGISTRY_FILE):
        return {}
    return json.load(open(REGISTRY_FILE))


def save(data):
    json.dump(data, open(REGISTRY_FILE, "w"))


def assign(branch):
    registry = load()
    used = set(registry.values())
    for port in PORT_RANGE:
        if port not in used:
            registry[branch] = port
            save(registry)
            return port
    raise Exception("No free ports")


def release(branch):
    registry = load()
    registry.pop(branch, None)
    save(registry)


def _container_status(name):
    result = subprocess.run(
        ["docker", "inspect", "-f", "{{.State.Status}}", name],
        capture_output=True, text=True
    )
    return result.stdout.strip() if result.returncode == 0 else None


def _container_logs(name, tail=80):
    result = subprocess.run(
        ["docker", "logs", "--tail", str(tail), name],
        capture_output=True, text=True
    )
    return (result.stdout + result.stderr).strip()


def _wait_ready(port, branch, retries=15, delay=2):
    container = f"simmsilos-{branch}"
    for i in range(retries):
        # fail fast if the container already died — no point polling localhost.
        status = _container_status(container)
        if status not in ("running", "created", None):
            logs = _container_logs(container)
            raise Exception(
                f"Container {container} exited (status={status}) before becoming ready.\n"
                f"--- last logs ---\n{logs}"
            )
        try:
            urllib.request.urlopen(f"http://localhost:{port}/health", timeout=2)
            print(f"Container ready on port {port}")
            return
        except Exception:
            print(f"Waiting for container... ({i+1}/{retries})")
            time.sleep(delay)
    raise Exception(f"Container on port {port} never became ready")


def spin_up(branch, image, env_file=".env", env_vars=None):
    container = f"simmsilos-{branch}"
    subprocess.run(["docker", "rm", "-f", container], capture_output=True)
    release(branch)
    port = assign(branch)
    cmd = [
        "docker", "run", "-d",
        "--name", container,
        "--network", DOCKER_NETWORK,
        "-p", f"{port}:3000",
        "-e", f"BRANCH={branch}",
    ]
    if os.path.exists(env_file):
        cmd += ["--env-file", env_file]
    for k, v in (env_vars or {}).items():
        cmd += ["-e", f"{k}={v}"]
    cmd.append(image)
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        release(branch)
        raise Exception(f"docker run failed: {result.stderr.strip()}")
    _sync_gateway()
    _wait_ready(port, branch)
    return port


def restart(branch, image, env_file=".env", env_vars=None):
    tear_down(branch)
    return spin_up(branch, image, env_file, env_vars)


def tear_down(branch):
    subprocess.run(["docker", "rm", "-f", f"simmsilos-{branch}"])
    release(branch)
    _sync_gateway()
    print(f"Port freed for branch {branch}")
